server:
  port: 7200
  forward-headers-strategy: framework
  tomcat:
    max-http-form-post-size: 10MB
spring:
  rabbitmq:
    host: 10.0.0.13
    port: 5672
    username: admin
    password: '{cipher}589803053f2b951bd45b83b28b9a83e5a8c0e1a5900e333bf10171fc29546c8a'
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
    openfeign:
      client:
        config:
          default:
            connectTimeout: 30000
            readTimeout: 30000
            loggerLevel: basic
  datasource:
    url: jdbc:mysql://10.0.0.8:3306/llmkt_test?useSSL=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: '{cipher}8d79ae6c1b062ded93b77c6112426d3ac61cd4b03e40b8b0cd31356101d66b7f'
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      idle-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 30000
      auto-commit: true
      pool-name: LlmktHikari
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
bucket-name: llmkt-test-1257926378