server:
  port: 7300
  forward-headers-strategy: framework
spring:
  rabbitmq:
    host: 10.0.0.13
    port: 5672
    username: admin
    password: '{cipher}589803053f2b951bd45b83b28b9a83e5a8c0e1a5900e333bf10171fc29546c8a'
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
  datasource:
    url: jdbc:mysql://10.0.0.8:3306/llmkt_test?useSSL=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: '{cipher}8d79ae6c1b062ded93b77c6112426d3ac61cd4b03e40b8b0cd31356101d66b7f'
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      idle-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 30000
      auto-commit: true
      pool-name: LlmktHikari
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.llmkt.publish: DEBUG
wechat:
  open:
    componentAppId: "{cipher}036df6d958cc0b546c3ab8ffb9527e6d54af029964a8338720aaef756b91a73c3c9b7c77733ef03e0d19f75eac0cc16c"
    componentSecret: "{cipher}9811794c98a84f047bebe84917844e216a914650d05e7dd19f434f6175c894bdae70741bdd56077d18adb0ed83b306283b060f2b44885b18003be443c3f1f043"
    componentToken: "{cipher}95781109059be618c260508c8f706407ddde43db6ef86449ff38d7dbd0fbb979"
    componentAesKey: "{cipher}d2318ec076fd7eb6fb7741dec6f1dd7e179531de6ab08761da31eda27776152ef149a57b103d1f9ef363cd18c5c648fb500d1ae155319452dbd6f2d0b6e3e6f7"
  redis:
    host: "10.0.0.13"
    password: "{cipher}8d79ae6c1b062ded93b77c6112426d3ac61cd4b03e40b8b0cd31356101d66b7f"